name: analyseur_live_flutter_5octobre2023
description: "A new Flutter project."

# Ce fichier permet d'indiquer les packages qu'on installe
# permet aussi d'incorporer des polices de caractères au projet
# permet aussi d'incorporer des images dans notre projet


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1


environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    # On pourra ajouter des extensions 
    # Une extension pour faire des requetes reseaux
    # une extension pour jouer un son 
    # ---------
    # Faire attention au tabulation


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Partie pour rajouter des images
assets:
  # section ou on indique à flutter ou se trouve notre police de caractères
  # example:
  fonts:
  # un tiret + un espace + family: Pacifico
    - family: Pacifico
      fonts:
        # deux espaces , on aligne le tiret sur le n de fonts
        - asset: fonts/Pacifico-Regular.ttf
  # quand on sauvegarde le fichier - flutter pub get


  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


